[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200

build_flags =
  -DBOARD_HAS_PSRAM
  -DCORE_DEBUG_LEVEL=0
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1

board_build.psram = enabled

lib_deps =
  adafruit/Adafruit MLX90640
  adafruit/Adafruit BusIO